### ISSUE TITLE
Item List Font?

### ISSUE THREAD

**Issue by SzadyDesigns** [ChernyshenkoTaras/TCPickerView#10]
It would be splendid if the item list font could be set, just like the title and button fonts.  I simply went in and just overrode the tableView titleLabel font in the source file, but having a public set-able variable would be beneficial.

**Comment by ChernyshenkoTaras** [comment]
@SzadyDesigns thanks for your feedback and sorry that I answer so late. I absolutely agree with you. I plan to add it in next version of this lib

**Comment by ChernyshenkoTaras** [comment]
Fixed this issue in version `0.1.9`
