### ISSUE TITLE
Close and Done Button action

### ISSUE THREAD

**Issue by ismailtosun** [ChernyshenkoTaras/TCPickerView#11]
Hi, thanks for this perfect lib.
My question is when i click done button i want to set action in it. How can i reach done button action ?

**Comment by ChernyshenkoTaras** [comment]
@ismailtosun hi,
it is easy, when user press `done` button `completionHandler` would be called. So you can set your own completion handler, like it is shown in example
```
picker.completion = { (selectedIndexes) in
    //your done button action is here
}
```

**Comment by ChernyshenkoTaras** [comment]
I will close this issue, because it seems like my solution is solved your problem. Feel free to open this issue again if there is still any problems
