### ISSUE TITLE
List is not sorted properly

### ISSUE THREAD

**Issue by pkasson** [ChernyshenkoTaras/TCPickerView#12]
After appending data the list is not sorted in append order.  Don't understand how to do the sort with the function provided:

  picker.values.sort(by: <#T##(TCPickerView.Value, TCPickerView.Value) throws -> Bool#>)

**Comment by ChernyshenkoTaras** [comment]
You can simply call `picker.values.sort { $0.title < $1.title }` but it is not good practice. Better solution will be sort your dataSource and only then set it to `picker.values`

**Comment by ChernyshenkoTaras** [comment]
I will close this issue, because it seems like my solution is solved your problem. Feel free to open this issue again if there is still any problems
