### ISSUE TITLE
pre selected values in TCPickerView

### ISSUE THREAD

**Issue by d33pak-s1ngh** [ChernyshenkoTaras/TCPickerView#14]
i have an object of TCPickerView and i want to set some pre selected values in it.
as per your suggestion in readme file following code can be use to set preselected value 

`TCPickerView.Value(title: "Chevrolet Bolt EV", isChecked: true)`
when i try to use this method 
`Value(title: "Chevrolet Bolt EV", isChecked: true)`
with my picker object it says "Static member 'Value' cannot be used on instance of type 'TCPickerView'"

so how should i use this method ?

**Comment by ChernyshenkoTaras** [comment]
Hey @d33pak-s1ngh ,
seems like you misunderstood it a little. `TCPickerView` doesn't has method Value(title: isChecked:) which could be used for pre-selection.

`TCPickerView.Value` it's a structure that is represent value that could be shown in picker. And it has `init` method `(title: String, isChecked: Bool = false)` which you need to use, if you want to allocate `TCPickerView.Value` object.

As you can see `isChecked` parameter has default implementation `false`, so if you want to preselect any item, then you need to set `isChecked` parameter for this item to `true`.

So if you want to preselect all items from example you need to do next

```
let picker = TCPickerView()
picker.title = "Cars"
let cars = [
    "Chevrolet Bolt EV",
    "Subaru WRX",
    "Porsche Panamera",
    "BMW 330e",
    "Chevrolet Volt",
    "Ford C-Max Hybrid",
    "Ford Focus"
]
let values = cars.map { TCPickerView.Value(title: $0, isChecked: true) }
picker.values = values
...
```

As you can see, when I was created values list `let values = cars.map { TCPickerView.Value(title: $0, isChecked: true) }`, I set `isChecked` parameter to `true`.

Hope it will help you!

**Comment by d33pak-s1ngh** [comment]
thank you @ChernyshenkoTaras  it helps a lot.
