### ISSUE TITLE
Pre-selected single value of String Array?

### ISSUE THREAD

**Issue by jabransiddiqui** [ChernyshenkoTaras/TCPickerView#15]
How can i achieve :  Pre-selected single value of String Array , i want to pass the string which i want to pre-select
if i do 
let cars = [
            "Chevrolet Bolt EV",
            "Subaru WRX",
            "Porsche Panamera",
            "BMW 330e",
            "Chevrolet Volt",
            "Ford C-Max Hybrid",
            "Ford Focus"
        ]
let values = cars.map {
            
            TCPickerView.Value(title:  "Chevrolet Bolt EV", ischecked : true)
            
        }

it display just one string "Chevrolet Bolt EV" and display all check value of cars array . 
please check.

**Comment by ChernyshenkoTaras** [comment]
Hi,
if I understood your problem correct, then it's simple. Here is a code from example:
```
let cars = [
            "Chevrolet Bolt EV",
            "Subaru WRX",
            "Porsche Panamera",
            "BMW 330e",
            "Chevrolet Volt",
            "Ford C-Max Hybrid",
            "Ford Focus"
        ]
        let values = cars.map { TCPickerView.Value(title: $0), isChecked: $0 == "BMW 330e" }
        picker.values = values
```

after you will show picker with `picker.show()` BMW 330e will be selected. Let me know if that resolve your issue.

**Comment by ChernyshenkoTaras** [comment]
@jibransiddiqui you can't just pass one string that should be preselected. Setup picker with array of strings that should be displayed and specify which one should be preselected by setting `isChecked ` parameter to `true` as I shown in my previous comment

**Comment by jabransiddiqui** [comment]
Thanks bro 👍🏻

**Comment by ChernyshenkoTaras** [comment]
You are welcome!
