### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [ChernyshenkoTaras/TCPickerView#25]
Hi @ChernyshenkoTaras  I am a graphics designer and i would like to contribute to your nice project by designing a logo for it. I already have ideas in mind and If you will allow me then i shall begin immediately. Thanks and best regards!

-Tobaloidee

**Comment by ChernyshenkoTaras** [comment]
Hi @Tobaloidee. It would be awesome!

**Comment by Tobaloidee** [comment]
Thanks for the positive feedback! I'll start designing and show you here when im done. :)

**Comment by Tobaloidee** [comment]
here's my design which is still open for your suggestions @ChernyshenkoTaras 

- design inpired by the illustrations in the readme file and expresses the feature of the project

i placed it in light & dark background to check its visibility in both

![pres-02](https://user-images.githubusercontent.com/36028424/43441659-2137ebd2-94ce-11e8-83a9-c5742ce55663.png)

**Comment by ChernyshenkoTaras** [comment]
Wow, I really like it! Could you create pull request with logo on top of readme?

**Comment by Tobaloidee** [comment]
Im glad you liked it! :) will finalize the files and upload and update the readme when i create a pull request..

**Comment by Tobaloidee** [comment]
here's the PR #26 @ChernyshenkoTaras  you can download all the versions and SVG-Ai-PNG formats of the logo on this [LINK](https://drive.google.com/drive/u/0/folders/1KFhmbpsIg9SO8JwuYrU75ca6HMDiX_5N)

Thanks and best regards! I hope to contribute on your other projects in the future..

- Tobaloidee

**Comment by ChernyshenkoTaras** [comment]
Thanks for contribution! You did a great work and I will be glad to work with you in future
