### ISSUE TITLE
Is there any way to provide select all option ?

### ISSUE THREAD

**Issue by d33pak-s1ngh** [ChernyshenkoTaras/TCPickerView#27]
Hii,  Is it possible to provide checkbox or button to select all option. when user will click on that button all the option in picker will be selected.

**Comment by ChernyshenkoTaras** [comment]
Hi,
it doesn't has such option. However you can download source code and add needed functionality by yourself

**Comment by d33pak-s1ngh** [comment]
@ChernyshenkoTaras  Thank you I have added this functionality. Following is how it looks.
[image 1](https://ibb.co/d7s27e)
[image 2](https://ibb.co/fn1Jfz)
[image 3](https://ibb.co/dECKne)

following is new file TCPickerView.swift which we have to update also need to add two icons in TCPPcikerView Resorces folder with name of "checked" and "unchecked"
[Source code file](https://github.com/d33pak-s1ngh/TCPickerView/blob/master/TCPickerView.swift)

**Comment by d33pak-s1ngh** [comment]
This will work only with .multiply selection mode. If selection mode is .single or .none then select all checkbox will be disappear and title occupy full container like a regular TCPPickerView
