### ISSUE TITLE
Is there a way to detect Cancel action?

### ISSUE THREAD

**Issue by amani-mohammad** [ChernyshenkoTaras/TCPickerView#28]
We have integrated this library with our project. But the problem now is that we need to get notified when 'Cancel' button is pressed so that we take some action.

Is there a method or call back we can call to do that ?

**Comment by ChernyshenkoTaras** [comment]
Thanks for your feedback. Please, check out new `0.2.6` version. I have added `closeAction` callback, use it to be notified when user pressed `Close` button.
