### ISSUE TITLE
Request to add custom id for each record title.

### ISSUE THREAD

**Issue by railsfactory-kumaresh** [ChernyshenkoTaras/TCPickerView#4]
Hi 

I am facing problem while populate the title list with checked state.  I am matching $0.name  == namevalue and then check the row. but if same name comes in list then its checked the another name also which is not actually selected previousaly.  If your provide option to title and id . Then I can match id and validate and check the particular tittle.

**Comment by ChernyshenkoTaras** [comment]
Hi @railsfactory-kumaresh and sorry for late response. I don't really understood why do you need `id` field. You populate data with array
```
let cars = [
    "Chevrolet Bolt EV",
    "Subaru WRX",
    "Porsche Panamera",
    "BMW 330e",
    "Chevrolet Volt",
    "Ford C-Max Hybrid",
    "Ford Focus"
]
```
so you have ordered list of values. `TCPickerView.Value` has to property 
```
	public let title: String
	public var isChecked: Bool
```
so you can set which values from your array should be selected from the begining.
After you checked some fields in picker you can get checked values from `completionHandler` like I shown in example:
```
picker.completion = { (selectedIndexes) in
    for i in selectedIndexes {
        print(values[i].title)
    }
}
```
completionHandler return selected indexes, and because array is a ordered list you can get checked values form this array by their indexes.

So, please, explain you issue more clearly with code snippets if possible

**Comment by railsfactory-kumaresh** [comment]
@ChernyshenkoTaras Thanks for your response. let me explain i am displaying the Employee Name list. Name list may contain same name. Ex. Kumaresh is employe name and same kumaresh will come in same list but actually that employee is different one. If i am select the first employee and open the picker it automatically select another kumaresh also by check mark.

if finding the index where the selected name by comparing the string value

 if let index = values.index(where: { $0.title == txtFldEmployeeName.text! }) {
}

So I need to different the name for that i required id to identify which is actually checked. I have modified the code based on that.

Add record_id in Value property. 
 public struct Value {
        public let title: String
        public var isChecked: Bool
        public var record_id: Int
        
      public init(title: String,record_id : Int, isChecked: Bool = false) {
            self.title = title
            self.record_id = record_id
            self.isChecked = isChecked
        }
    }

var values = empList.map { TCPickerView.Value(title: $0.emp_name, record_id: $0.emp_id) }
      if let index = values.index(where: { $0.title == txtFldEmployeeName.text! }) { // **find index of array which is selected**
        if empList[index].emp_id == values[index].record_id { //**checking the id for which employee name actually selected**
          values.remove(at: index)
          values.insert(TCPickerView.Value.init(title: txtFldEmployeeName.text!, record_id: values[index].record_id, isChecked: true), at: index)
          picker.values = values
        }
      }else{
        picker.values = values
      }

Like above code i am selecting the employee name programmatically.

Kindly let me know any another way to manage the repeated name in the list.

**Comment by ChernyshenkoTaras** [comment]
@railsfactory-kumaresh what is a `txtFldEmployeeName.text!`?
Nevertheless, `values` and `empList` has same order. You can get index of selected `employeeID` from `empList` and use this index to mark checked employee in picker

**Comment by railsfactory-kumaresh** [comment]
@ChernyshenkoTaras  In design i have TextField to show the selected employee name (like kumaresh and 2 other selected). On selection as you said i get the employee id based on the index thats fine. Now i click the textfield to open the Picker here i have to display the selected employe by checked. 

EmpList = [{Emp_name : Kumaresh, emp_id: 105},{Emp_name : ChernyshenkoTaras, emp_id: 115},{Emp_name : Kumaresh, emp_id: 235}]

Take an example i have emplist array like above. While displaying the the name in picker i have to filter only name like this 
var values = empList.map { TCPickerView.Value(title: $0.emp_name) }
Here values holds only employe name list[Kumaresh, ChernyshenkoTaras, Kumaresh]  and i selected first employee name and displayed in TextField(txtFldEmployeeName) like Kumaresh.

While open the picker again I have to check the selected employee. Now its checked both kumaresh employee name based on string match, here i could not match the employee id and no provision to check with id.
if let index = values.index(where: { $0.title == txtFldEmployeeName.text! }) {
}

**Comment by ChernyshenkoTaras** [comment]
@railsfactory-kumaresh why do you store employee name and not employee id?
after you have selected employee `UIPickerView` will return his index in completionHandler:
```
picker.completion = { (selectedIndexes) in
    
}
```

depends on `selectedIndexes` you can get appropriate employees  from `EmpList`, so you can store their `emp_id `.
Now, when you will open the picker again you need to set employees, which `emp_id` was stored, as `checked`.

**Comment by railsfactory-kumaresh** [comment]
I have to display all the employees(not selected one) and show checked which one selected already.

picker.completion = { (selectedIndexes) in
    
}
completion flow is fine. i have no doubt on that. 

While open the picker again with in all employee list and i have show checked state

**Comment by ChernyshenkoTaras** [comment]
@railsfactory-kumaresh  so what is a problem to show which one is selected open the picker again?
just iterate thru employees and if employeID was stored than it checked. Init `TCPickerView.Value` with constructor `TCPickerView.Value(title: $0, isChecked: {if employeID was stored than it true, else it is false})`

**Comment by railsfactory-kumaresh** [comment]
@ChernyshenkoTaras Will try and update you the same.
