### ISSUE TITLE
Error in the text customization of the Close button:

### ISSUE THREAD

**Issue by RodrigoSMarques** [ChernyshenkoTaras/TCPickerView#6]
Hello, I found an error in the text customization of the Close button:

    open var closeText: String = "Close" {
        didSet {
            self.doneButton?.setTitle(self.closeText, for: .normal)
        }
    }

**Comment by ChernyshenkoTaras** [comment]
@rodrigosmarques thanks for your bug report, I really appreciate it.

**Comment by ChernyshenkoTaras** [comment]
Fixed this issue in version `0.1.9`
