### ISSUE TITLE
Multiline Text display 

### ISSUE THREAD

**Issue by railsfactory-kumaresh** [ChernyshenkoTaras/TCPickerView#8]
How to display multiline text ?. right now its showing only one line. i want to display multiline text. 

Kindly dynamic  the tableview cell height based on the titlelabel text.

**Comment by ChernyshenkoTaras** [comment]
I will think about this functionality. Right now it looks for me as a bad idea from design side. From the beginning I had idea to create picker where all cells would have same height.

But anyway I will think for possibility to use own cells inside picker

**Comment by ChernyshenkoTaras** [comment]
Added possibility to use own designed cells
