### ISSUE TITLE
Uncheck Selected Item

### ISSUE THREAD

**Issue by railsfactory-kumaresh** [ChernyshenkoTaras/TCPickerView#9]
Kindly provide uncheck option which is already selected. 

1. For Single selection 
2. I already selected one item and displayed in textField 
3. Expected : I want to clear the item in textField so in picker we need deselect the item and click Done.

**Comment by ChernyshenkoTaras** [comment]
@railsfactory-kumaresh thanks for youк interest in my library. TCPickerView should not be responsible for setting selected/unselected state to items. Basically it is just a view what is responsible for showing items, and depends on user interaction on this view it show checkmark or hide it.

For your issue, you need to implement some data source in your controller. It will hold all values/ or values indexes of selected items.
Once you select some items in TCPickerView add this items indexes into your data source. And once something should be unselected - remove it from your data source.
